version : "3.3"
services:
  nginx:
    image: nginx  # 존재하는 nginx 이미지 사용
    container_name: nginx   # Nginx Container 이름 지정
    ports:
      - 80:80
    volumes:
      - /etc/nginx/:/etc/nginx/      # EC2 Nginx와 Docker Nginx Container 를 매핑
  database:
    image: mysql:8.0.30
    restart: always
    container_name: database
    environment:
      MYSQL_DATABASE: project
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - springboot-mysql-net
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - database
    container_name: app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://52.79.162.144:3306/project?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    networks:
      - springboot-mysql-net
networks:
  springboot-mysql-net:
    driver: bridge

