version : "3.3"
services:

  database:
    image: mysql:8.0.30
    restart: always
    container_name: database
    environment:
      MYSQL_DATABASE: project
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - springboot-mysql-net
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - database
    container_name: app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://52.79.162.144:3306/project?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    networks:
      - springboot-mysql-net
  nginx:
    container_name: nginx
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
        - "80:80"
    depends_on:
        - app
    networks:
        - springboot-mysql-net
networks:
  springboot-mysql-net:
    driver: bridge

