version : "3.3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    container_name: app
    environment:
      SPRING_DATASOURCE_URL:
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - springboot-mysql-net

networks:
  springboot-mysql-net:
    driver: bridge

