services:
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      -  ./mysql/mysql_data:/var/lib/mysql
    platform: linux/x86_64
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - 3307:3306
    networks:
      - springboot-mysql-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10
  redis:
    image: redis:alpine
    ports:
      - "6381:6379"
    volumes:
      - ./data/redis:/data
    networks:
      - springboot-mysql-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
  backend:
    image: ${DOCKERHUB_USERNAME}/study_project:latest
    restart: always
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATASOURCE_DRIVER: com.mysql.cj.jdbc.Driver
    container_name: app
    networks:
      - springboot-mysql-net
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus-prod.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - springboot-mysql-net
      - monitoring
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}


networks:
  springboot-mysql-net:
    driver: bridge
  monitoring:
    driver: bridge
