spring:
  profiles:
    active: local


---
spring:
  profiles:
    activate:
      on-profile: local

---
spring:
  profiles:
    activate:
      on-profile: prod

---
spring:
  profiles:
    activate:
      on-profile: dev
---

spring :
 config:
  import:
    - optional:file:./.env
  output:
    ansi:
      enabled: always

dotenv:
  enabled: true

jwt:
  secret: ${JWT_SECRET}
  token-validity-in-seconds: 86400
