spring:
  profiles:
    active: local



---
spring:
  profiles:
    activate:
      on-profile: local

---
spring:
  profiles:
    activate:
      on-profile: prod

---
spring:
  profiles:
    activate:
      on-profile: dev
---
jwt:
  secret: ${JWT_SECRET}
  token-validity-in-seconds: 86400


spring :
  output:
    ansi:
      enabled: always

dotenv:
  enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,loggers,prometheus
  endpoint:
    health:
      show-details: always

      # localhost:8080/actuator


