server:
  port: 8080
  address: 0.0.0.0

spring:
  datasource:
    url: jdbc:h2:tcp://db:1521/bookstore
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true
  data:
    redis:
      host: redis
      port: 6379

