spring:
  profiles:
    active: local



---
spring:
  profiles:
    activate:
      on-profile: local
  sql:
    init:
      mode: always
      platform: local          # data-local.sql 을 찾도록 지정
  jpa:
    defer-datasource-initialization: true   # 테이블 생성 후 data-local.sql 실행되도록


---
spring:
  profiles:
    activate:
      on-profile: prod

---
spring:
  profiles:
    activate:
      on-profile: dev
---
jwt:
  secret: ${JWT_SECRET}
  token-validity-in-seconds: 86400


spring :
  output:
    ansi:
      enabled: always

dotenv:
  enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,loggers,prometheus
  endpoint:
    health:
      show-details: always

      # localhost:8080/actuator


