spring:
  profiles:
    active: local


---
spring:
  profiles:
    activate:
      on-profile: local

---
spring:
  profiles:
    activate:
      on-profile: prod

---
spring:
  profiles:
    activate:
      on-profile: dev
---

spring :
 config:
  output:
    ansi:
      enabled: always

dotenv:
  enabled: true


