server:
  port: 8000

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/bookstore
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true
  data:
    redis:
      host: localhost
      port: 6379
