spring:
  datasource:
<<<<<<< HEAD
    url: jdbc:mysql://52.79.162.144:3306/project
=======
    url: jdbc:mysql://3.36.59.194:3306/project
>>>>>>> e0369b9da9ba64313da1acedce215afc1b0d55d0
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: study
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true

jwt:
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400

logging:
  level:
    me.silvernine: DEBUG