location: http://localhost:3000/
server:
  port: 8000

spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/bookstore
    username: sa
    password:
    hikari:
      # 최소 유휴 커넥션 수
      minimum-idle: 5
      # 최대 커넥션 풀 크기
      maximum-pool-size: 10
      # 커넥션 타임아웃 (밀리초)
      connection-timeout: 30000
      # 커넥션 최대 유효 시간 (밀리초)
      max-lifetime: 600000
      # 커넥션 풀의 유휴 커넥션 검사 주기 (밀리초)
      idle-timeout: 300000
      # 커넥션 풀에서 커넥션을 테스트할 SQL
      connection-test-query: SELECT 1
      # 커넥션 풀의 초기화 대기 시간 (밀리초)
      initialization-fail-timeout: 1
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true
  data:
    redis:
      host: localhost
      port: 6379
      lettuce:
        shutdown-timeout: 100ms  # 연결 종료 대기 시간
  security:
    oauth2:
      client:
        registration:
          kakao:
            authorization-grant-type: authorization_code
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: ${KAKAO_REDIRECT_URI}
            scope:
              - account_email
              - profile_nickname
            client-authentication-method: client_secret_post
            client-name: Kakao
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            redirect-uri: ${NAVER_REDIRECT_URI}
            authorization-grant-type: authorization_code
            scope: name, email
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
jwt:
  secret: ${JWT_SECRET}
  token-validity-in-seconds: 86400

logging:
  level:
    org:
      springframework:
        web: DEBUG
    org.springframework.security: DEBUG
