spring:
  profiles:
    active: local
---
spring:
  profiles:
    activate:
      on-profile: local


---
spring:
  profiles:
    activate:
      on-profile: prod

---

jwt:
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400

logging:
  level:
    root: info



