spring:
  profiles:
    active: local


---
spring:
  profiles:
    activate:
      on-profile: local

---
spring:
  profiles:
    activate:
      on-profile: prod

---
spring:
  profiles:
    activate:
      on-profile: dev
---
jwt:
  secret: ${JWT_SECRET}
  token-validity-in-seconds: 86400


spring :
  output:
    ansi:
      enabled: always

dotenv:
  enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher



