spring:
  profiles:
    active: local
  config:
    import:
      - optional:file:./.env

---
spring:
  profiles:
    activate:
      on-profile: local

---
spring:
  profiles:
    activate:
      on-profile: prod

---
spring:
  profiles:
    activate:
      on-profile: dev
---

dotenv:
  enabled: true

jwt:
  secret: ${jwt}
  token-validity-in-seconds: 86400
spring:
  output:
    ansi:
      enabled: always
